In syscalls.py now
firstcall called with 5 arguments
The time is now Mon Aug 28 12:28:33 2006
firstcall exited with status 1
firstcall called with 5 arguments
The time is now Mon Aug 28 12:28:34 2006
The process ID is fake
