
class MyException(Exception):
    pass

class BadCallException(MyException):
    pass
