<-PYT:import urllib2
<-PYT:urllib2.urlopen('foo://no.such.site')
->RET:raise Instance('URLError(exceptions.IOError)', 'urlerror1')
<-PYT:urlerror1.args
->RET:('No such site, you wally!',)
<-PYT:urllib2.urlopen('foo://another.no.such.site')
->RET:raise Instance('URLError(exceptions.IOError)', 'urlerror2')
<-PYT:urlerror2.__str__()
->RET:"<urlopen error (-2, 'Now you're really getting on my nerves!')>"
